/**
 * WebApi
 * apis for webUI
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.shadowmask.web.model

case class MaskRule (
  id: Option[String],
  name: Option[String],
  desc: Option[String],
  params: Option[List[MaskRuleParam]]
)
